replicaCount: 1

image:
  repository: alihashempour/kaas-api
  pullPolicy: IfNotPresent
  tag: "1.2"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: "kaas-api"

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: [ ]

volumeMounts: [ ]


nodeSelector: { }

tolerations: [ ]

affinity: { }

monitoringJob:
  image:
    repository: monitoring-job
    tag: "1.0"
  schedule: "*/5 * * * *"

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: latest
  database: monitoring
  storageSize: 5Gi

