apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-resource-manager-binding
subjects:
  - kind: ServiceAccount
    name: kaas-api-release
    namespace: default
roleRef:
  kind: ClusterRole
  name: all-resource-manager
  apiGroup: rbac.authorization.k8s.io
