apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp-monitor-role-binding
subjects:
  - kind: ServiceAccount
    name: myapp-cronjob-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: myapp-monitor-role
  apiGroup: rbac.authorization.k8s.io
