apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaas-api.fullname" . }}-postgres
  labels:
    app: {{ include "kaas-api.name" . }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ include "kaas-api.fullname" . }}-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kaas-api.fullname" . }}-postgres
  labels:
    app: {{ include "kaas-api.name" . }}
spec:
  serviceName: "{{ include "kaas-api.fullname" . }}-postgres"
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kaas-api.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "kaas-api.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "kaas-api.fullname" . }}-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kaas-api.fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}
