apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaas-api.fullname" . }}-postgres-secret
  labels:
    app: {{ include "kaas-api.name" . }}
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
